[package]
name = "hera"
version = "0.1.0"
authors = ["Alex Beregszaszi <alex@rtfs.hu>"]
license = "Apache-2.0"
repository = "https://github.com/ewasm/hera.rs"
description = "Hera rewritten in Rust"

[lib]
name = "hera"
crate-type = ["staticlib", "dylib"]
